config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"

  resources :users, only: [:index, :show, :destroy, :edit, :update]

  resources :restaurants, only: [
    :index, :show, :new, :edit,
    :create, :update, :destroy
  ] do
    resources :reviews, only: [:show, :create, :destroy, :edit, :new, :update]
  end

  resources :reviews, only: [:edit, :update] do
    resources :upvotes, only: [:new, :create, :edit, :update]
    resources :downvotes, only: [:new, :create, :edit, :update]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  has_many :reviews, dependent: :destroy
  has_many :restaurants, dependent: :destroy
  has_many :votes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants

  def admin?
    role == "admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, except: [:create, :new, :update, :index]

  def index
    authorize_admin
    @users = User.order("email ASC").page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User updated!"
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted!"
    redirect_to users_path
  end

  private

  def authorize_user
    unless current_user.admin? || current_user == User.find(params[:id])
      not_found
    end
  end

  def authorize_admin
    unless current_user.admin?
      not_found
    end
  end

  def user_params
    params.require(:user).permit(:email, :role, :avatar, :name, :remove_avatar)
  end
end

app/views/users/edit.html.erb
<div class="container registration">
  <div class="page-header"><h1>Edit User</h1></div>
  <div class="row">
    <div class="col-sm-4">
      <%= image_tag(@user.avatar.thumb.url, class: "top-picks edit-profile") %>
      <%= button_to "Delete User", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "edit-profile" %>
    </div>
    <div class="col-sm-8">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for @user do |f| %>
        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true %>
        </div>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>

        <p>
          <%= f.label :role %><br>
          <%= f.select :role, options_for_select(["user", "admin"]) %>
        </p>

        <div class="field">
          <%= f.label :avatar %><br />
          <%= f.file_field :avatar %>
        </div><br />

        <div class="field">
          <% if @user.avatar.url.present? %>
            <%= image_tag(@user.avatar.small_thumb.url, class: "top-picks") %>
            <%= f.label :remove_avatar do %>
              <%= f.check_box :remove_avatar %> <i>Remove image</i>
            <% end %>
          <% end %>
        </div>

        <p class="button">
          <%= f.submit %>
        </p>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container registration">
  <div class="page-header"><h1>Users</h1></div>
  <div class="row">
    <table>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag(user.avatar.small_thumb.url, class: "top-picks") %>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= button_to "Edit", edit_user_path(user), method: :get, class: "admin-buttons" %></td>
          <td><%= button_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "admin-buttons" %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="page-header"><h1><%= @user.name %></h1></div>
  <div class="row">
    <div class='col-sm-4'>
      <%= image_tag(@user.avatar.thumb.url, class: "top-picks edit-profile") %><br />
      <% if current_user.admin? %>
        <%= button_to "Edit user", edit_user_path(@user), method: :get, class: "edit-profile" %>
      <% else %>
        <%= button_to "Edit account", edit_user_registration_path(@user), method: :get, class: "edit-profile" %>
      <% end %>
    </div>
    <div class='col-sm-4'>
      <table>
        <tr>
          <th>Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= mail_to(@user.email) %></td>
        </tr>
        <tr>
          <th>Member since</th>
          <td><%= @user.created_at %></td>
        </tr>
      </table>
      <br /><br />
      <% @user.reviews.each do |review| %>
        <div class="review-border">
          User's review of: <%= link_to review.restaurant.name, restaurant_path(review.restaurant.id) %>
          <br /><br />
          <p><%= review.body %></p>
        </div>
     <% end %>
    </div>
  </div>
</div>