config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"

  resources :users, only: [:index, :show, :destroy, :edit, :update]

  resources :restaurants, only: [
    :index, :show, :new, :edit,
    :create, :update, :destroy
  ] do
    resources :reviews, only: [:show, :create, :destroy, :edit, :new, :update]
  end

  resources :reviews, only: [:edit, :update] do
    resources :upvotes, only: [:new, :create, :edit, :update]
    resources :downvotes, only: [:new, :create, :edit, :update]
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
  belongs_to :category
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  def average_rating
    if reviews.count > 0
      reviews.sum(:rating) / reviews.count
    else
      1
    end
  end

  def self.top_restaurants
    top_hash = {}
    top_array = []
    restaurants = Restaurant.all
    restaurants.each do |restaurant|
      top_hash[restaurant] = restaurant.average_rating
    end
    top_array << top_hash.sort_by { |k, v| -v }.first(3)
    top_array.flatten(1)
  end

  def parse_for_google_maps
    @google_map_params = [street_address, city, state].join(" ")
    @google_map_params.gsub!(" ", "+")
  end

  def editable_by?(current_user)
    current_user.role == "admin" || current_user == user
  end

  def self.search(query)
    sql = %Q{
      restaurants.name ILIKE ?
      or restaurants.description ILIKE ?
      or reviews.body ILIKE ?
    }
    Restaurant.joins(:reviews).where(
      [sql, "%#{query}%", "%#{query}%", "%#{query}%"]
    ).distinct
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authorize_user, except: [:index, :show, :create, :new]

  def index
    @google_maps_url = 'https://www.google.com/maps/embed/v1/place?key=' + ENV["GOOGLE_MAPS_API_KEY"] + '&q=Chinatown+Boston+MA'
    if params[:search_text].present?
      @restaurants =
        Restaurant.search(params[:search_text]).order("name ASC")
        .page(params[:page])
    else
      @restaurants = Restaurant.order("name ASC").page(params[:page])
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @google_maps_url = %Q{
      https://www.google.com/maps/embed/v1/place?key=
      #{ENV["GOOGLE_MAPS_API_KEY"]}&q=#{@restaurant.parse_for_google_maps}
    }
    @reviews = @restaurant.reviews.page(params[:page])
  end

  def new
    @restaurant = current_user.restaurants.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "Restaurant created!"
      redirect_to @restaurant
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant updated!"
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = "Restaurant deleted!"
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name, :street_address, :city, :state, :zip_code, :description,
      :phone, :reservations, :delivery, :category_id, :user_id, :photo
      )
  end

  def authorize_user
    @restaurant = Restaurant.find(params[:id])
    user_signed_in? && @restaurant.editable_by?(current_user)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :street_address %><br>
    <%= f.text_area :street_address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.select :state, options_for_select(CountryStateSelect::Constant::USA_STATES) %>
  </p>

  <p>
    <%= f.label :zip_code %><br>
    <%= f.text_area :zip_code %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </p>

  <p>
    <%= f.label :reservations %><br>
    <%= f.select :reservations, [['No', false], ['Yes', true]] %>
  </p>

  <p>
    <%= f.label :delivery %><br>
    <%= f.select :delivery, [['No', false], ['Yes', true]] %>
  </p>
  
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div class="col-sm-6 restaurant">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">
        <%= link_to restaurant.name, restaurant_path(restaurant) %>
      </h2>
    </div>
    <div class="panel-body lead review-window">
      <div class="col-xs-6">
        <% if restaurant.photo.url %>
          <%= image_tag(restaurant.photo.thumb.url, class: "top-picks") %>
        <% else %>
          <img class="placeholder" src="assets/restaurant_placeholder.png">
        <% end %>
      </div>
      <div class="col-xs-6">
        <%= restaurant.description %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div id="home" class="home">
  <div class="text-vcenter">
    <h3 class="landing">boston<span class="landing-strong-red">CHINA</span></h3>
    <h3 class="landing"><span class="landing-strong">TOWN</span>best<span class="red-text">eats</span></h3>
  </div>
</div>

<!-- second section - About -->
<div class="red-border"></div>
<div id="about" class="pad-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <iframe src=<%= @google_maps_url %>></iframe>
        <!-- <img class = "top-picks" src="assets/placeholder.jpg" alt="" /> -->
      </div>
      <div class="col-sm-6 text-center" id="next-to-map">
        <h2>The best (and worst) that Boston's Chinatown has to offer.</h2>
      </div>
    </div>
  </div>
</div>
<!-- /second section -->

<!-- third section - Services -->
<div id="services" class="pad-section">
  <div class="container">
    <h2 class="text-center">Today's Top Picks</h2> <hr />
    <div class="row text-center">
      <% Restaurant.top_restaurants.each do |restaurant| %>
        <div class="col-sm-4 col-xs-6">
          <% if restaurant[0].photo.url %>
            <%= image_tag(restaurant[0].photo.thumb.url, class: "top-picks") %>
          <% else %>
            <%= image_tag "restaurant_placeholder.png", class: "placeholder" %>
          <% end %>
          <div class="top-pick-name">
            <h4><%= link_to restaurant[0].name, restaurant_path(restaurant)%></h4>
          </div>
          <div class="rice-bowl">
            <img src="assets/bowl-<%= restaurant[0].average_rating %>.png">
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- /third section -->

<!-- fourth section - Information -->

<div id="information" class="pad-section">
  <div class="container" id="restaurants">
    <div class="col-xs-12" id="restaurant-buttons">
      <div class="pull-left grey actions">
        <%= form_tag root_path, method: :get do %>
          <%= text_field_tag :search_text %>
          <%= submit_tag "Search", class: "search" %>
        <% end %>
      </div>
      <div class="pull-right grey actions">
        <% if user_signed_in? %>
          <%= button_to 'New restaurant', new_restaurant_path, method: :get %>
        <% else %>
        <div class="sign-in">
          <p>Please<%= link_to ' sign in', new_user_session_path %> to create a new restaurant</p>
          </div>
        <% end %>
      </div>
    </div>
    <br />
    <br />

    <div class="row page">
      <%= render @restaurants %>
    </div>
  </div>

  <%= paginate @restaurants %>

</div>
<!-- /fourth section -->

app/views/restaurants/index.js.erb
$("#restaurants").append("<div class='page'><%= escape_javascript(render(@restaurants)) %></div>");

app/views/restaurants/new.html.erb
<div class='container'>
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<!--  -->
<!-- Restaurant Name -->
<!--  -->

<div id="restaurant-show-name" class="home">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="horizontal">
          <div class="vertical">
            <% if @restaurant.photo.url %>
              <%= image_tag(@restaurant.photo.url, class: "top-picks", id: "restaurant-picture") %>
          <% else %>
            <%= image_tag "restaurant_placeholder.png", class: "placeholder" %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="text-vcenter" id="restaurant-name">
          <h3 class="landing"><span class="landing-strong-red"><%= @restaurant.name %></span></h3>
        </div>
      </div>
    </div>
  </div>
</div>

<!--  -->
<!-- Map and Contact Info -->
<!--  -->
<div class="red-border"></div>
<div id="about" class="pad-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <iframe src="<%= @google_maps_url %>"></iframe>
      </div>
      <div class="col-sm-6 text-left">
        <div class="horizontal">
          <div class="vertical" id="contact-info">
            <table class="contact-info">
              <tr>
                <th>Address:</th>
                <td><%= @restaurant.street_address %></td>
              </tr>
              <tr>
                <th>City:</th>
                <td><%= @restaurant.city %></td>
              </tr>
              <tr>
                <th>State:</th>
                <td><%= @restaurant.state %></td>
              </tr>
              <tr>
                <th>Zip-code</th>
                <td><%= @restaurant.zip_code %></td>
              </tr>
              <tr>
                <th>Reservations:</th>
                <td><%= @restaurant.reservations ? "Yes" : "No" %></td>
              </tr>
              <tr>
                <th>Delivery:</th>
                <td><%= @restaurant.delivery ? "Yes" : "No" %></td>
              </tr>
              <tr>
                <th>Phone:</th>
                <td><%= @restaurant.phone %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--  -->
<!-- Description -->
<!--  -->

<div id="services" class="pad-section">
  <div class="container">
    <h2 class="text-center">About this restaurant...</h2> <hr />
    <h4 class="text-center"><%= @restaurant.description %></h4>
  </div>
</div>

<!--  -->
<!-- Reviews -->
<!--  -->

<div id="information" class="pad-section">
  <div class="container" id="reviews">
    <div class="col-xs-12 review-buttons">
      <div class="pull-right grey">
        <div class="actions" id="review-buttons">
          <% if user_signed_in? %>
            <% if @restaurant.editable_by?(current_user) %>
              <%= button_to 'Edit restaurant', edit_restaurant_path(@restaurant), method: :get %>
              <br />
              <%= button_to 'Delete restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            <%= button_to 'Write Review', new_restaurant_review_path(@restaurant), method: :get %>
          <% else %>
          <div class="sign-in">
            <p>Please<%= link_to ' sign in', new_user_session_path %> to write a new review</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <br />
    <br />

    <div class="row page">
      <%= render @reviews, locals: { reviews: @reviews } %>
    </div>
  </div>

  <%= paginate @reviews %>

</div>

app/views/restaurants/show.js.erb
$("#reviews").append("<div class='page'><%= escape_javascript(render(@reviews)) %></div>");