config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"

  resources :users, only: [:index, :show, :destroy, :edit, :update]

  resources :restaurants, only: [
    :index, :show, :new, :edit,
    :create, :update, :destroy
  ] do
    resources :reviews, only: [:show, :create, :destroy, :edit, :new, :update]
  end

  resources :reviews, only: [:edit, :update] do
    resources :upvotes, only: [:new, :create, :edit, :update]
    resources :downvotes, only: [:new, :create, :edit, :update]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize_user, except: [:create, :new]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      UserMailer.review_alert_email(@restaurant.user).deliver_later
      flash[:notice] = "Review Created!"
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])

    if @review.user_id == current_user.id
      @review.destroy
      flash[:notice] = "Review Deleted!"
      redirect_to restaurant_path(@restaurant)
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant

    if @review.update(review_params)
      flash[:notice] = "Review updated!"
      redirect_to @restaurant
    else
      render :edit
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body, :photo)
  end

  def authorize_user
    @review = Review.find(params[:id])
    user_signed_in? && @review.editable_by?(current_user)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for [ @restaurant , @review ] do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this review from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>

  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <p>
    <%= f.label :rating %> <br>
    <% Review::RATINGS.each do |c| %>
      <%= f.radio_button(:rating, c)%>
      <%= f.label("rating_#{c}", c) %>
    <% end %>
  </p>

  <%= f.submit%>
  <% end %>

app/views/reviews/_review.html.erb
<div class="col-sm-6 review">
  <div class="panel panel-default" id="review-panel">
    <div class="panel-heading">
      <div class="rice-bowl">
        <img src="../assets/bowl-<%= review.rating %>.png">
      </div>
      <!-- <p>Rating: <%= review.rating %></p> -->
    </div>
    <div class="panel-body lead">
      <div class="col-xs-4 review-user-info">
      <% if review.user.avatar.thumb.url %>
        <%= image_tag(review.user.avatar.thumb.url, class: "review-user-avatar top-picks") %>
        <% end %>
        <p class="red-text"><%= review.user.name %></p>
        <p>Joined on <%= review.user.created_at.strftime("%d %b %y") %></p>
        <% if user_signed_in? %>
          <%= button_to "", review_upvotes_path(review), id: "upvote" %>
          <p>Score: <%= review.score %></p>
          <%= button_to "", review_downvotes_path(review), id: "downvote" %>
          <% if review.editable_by?(current_user) %>
            <p>
              <%= link_to 'Edit', edit_restaurant_review_path(review.restaurant_id, review.id), class: "edit-delete" %> |
              <%= link_to 'Delete', restaurant_review_path(review.restaurant_id, review.id),
                method: :delete,
                data: { confirm: 'Are you sure?' }, class: "edit-delete" %>
            </p>
          <% end %>
        <% end %>
      </div>
      <div class="col-xs-8 review-content">
        <div class="review-window">
          <p><%= review.body %></p>
          <%= image_tag(review.photo.thumb) %>
        </div>
        <p class="review-timestamp">Reviewed at: <%= review.created_at.strftime("%l:%M %P %d %b %y") %></p>
        <% if review.created_at != review.updated_at %>
          <p class="review-timestamp red-text edit">Edited: <%= review.updated_at.strftime("%l:%M %P %d %b %y") %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<p><strong>Edit your review of <%= @restaurant.name %></p></strong>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/reviews/new.html.erb
<div class='container'>
<p><strong>Write your review of <%= @restaurant.name %></p></strong>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

</div>